import { CadBlock } from '../types.ts';

export const PREDEFINED_CAD_BLOCKS: CadBlock[] = [
  // SÉJOUR & REPAS
  {
    id: 'block-table-dining-6p',
    name: 'Table Repas 6 Places',
    category: 'sejour',
    widthMm: 1800,
    heightMm: 900,
    defaultLayer: 'mobilier',
    icon: 'table_restaurant',
    description: 'Table rectangulaire 1.80m x 0.90m avec 6 chaises disposées',
    renderType: 'table',
  },
    {
    id: 'baba-blocle-1',
    name: 'baba table Repas 6 Places',
    category: 'sejour',
    widthMm: 1800,
    heightMm: 900,
    defaultLayer: 'mobilier',
    icon: 'table_restaurant',
    description: 'Table rectangulaire 1.80m x 0.90m avec 6 chaises disposées',
    renderType: 'table',
  },
  {
    id: 'block-sofa-corner-3p',
    name: 'Canapé d\'Angle 4 Places',
    category: 'sejour',
    widthMm: 2400,
    heightMm: 1600,
    defaultLayer: 'mobilier',
    icon: 'weekend',
    description: 'Canapé panoramique avec méridienne réversible',
    renderType: 'sofa',
  },
  {
    id: 'block-coffee-table',
    name: 'Table Basse Salon',
    category: 'sejour',
    widthMm: 1100,
    heightMm: 600,
    defaultLayer: 'mobilier',
    icon: 'table_view',
    description: 'Table basse design en bois massif et verre',
    renderType: 'table',
  },
  {
    id: 'block-tv-unit',
    name: 'Meuble TV & Média',
    category: 'sejour',
    widthMm: 2000,
    heightMm: 450,
    defaultLayer: 'mobilier',
    icon: 'tv',
    description: 'Banc média suspendu 2.00m',
    renderType: 'generic',
  },

  // CUISINE & ÉLECTROMÉNAGER
  {
    id: 'block-kitchen-island',
    name: 'Îlot Central Cuisine + Évier',
    category: 'cuisine',
    widthMm: 2400,
    heightMm: 1000,
    defaultLayer: 'mobilier',
    icon: 'countertops',
    description: 'Îlot bar avec cuve sous plan et espace tabourets',
    renderType: 'island',
  },
  {
    id: 'block-sink-double',
    name: 'Évier Inox Double Bac',
    category: 'cuisine',
    widthMm: 1160,
    heightMm: 500,
    defaultLayer: 'mobilier',
    icon: 'faucet',
    description: 'Évier 2 bacs avec égouttoir rainuré',
    renderType: 'sink',
  },
  {
    id: 'block-cooktop-induction',
    name: 'Plaque Induction 4 Feux',
    category: 'cuisine',
    widthMm: 800,
    heightMm: 520,
    defaultLayer: 'mobilier',
    icon: 'outdoor_grill',
    description: 'Table induction affleurante avec zone flexible',
    renderType: 'generic',
  },

  // CHAMBRE & SUITE
  {
    id: 'block-bed-king',
    name: 'Lit King Size (180x200)',
    category: 'chambre',
    widthMm: 1900,
    heightMm: 2100,
    defaultLayer: 'mobilier',
    icon: 'bed',
    description: 'Lit double 180x200 avec tête de lit et chevets intégrés',
    renderType: 'bed',
  },
  {
    id: 'block-bed-queen',
    name: 'Lit Queen Size (160x200)',
    category: 'chambre',
    widthMm: 1700,
    heightMm: 2100,
    defaultLayer: 'mobilier',
    icon: 'single_bed',
    description: 'Couchage 160x200 avec 2 oreillers ergonomiques',
    renderType: 'bed',
  },
  {
    id: 'block-wardrobe',
    name: 'Dressing Coulissant 3 Portes',
    category: 'chambre',
    widthMm: 2500,
    heightMm: 650,
    defaultLayer: 'mobilier',
    icon: 'shelves',
    description: 'Armoire dressing pleine hauteur 2.50m',
    renderType: 'generic',
  },

  // SALLE DE BAIN & SANITAIRE
  {
    id: 'block-bath-island',
    name: 'Baignoire Îlot Ovale',
    category: 'sanitaire',
    widthMm: 1700,
    heightMm: 800,
    defaultLayer: 'mobilier',
    icon: 'bathtub',
    description: 'Baignoire monobloc acrylique blanc mat',
    renderType: 'bath',
  },
  {
    id: 'block-walkin-shower',
    name: 'Douche Italienne 120x90',
    category: 'sanitaire',
    widthMm: 1200,
    heightMm: 900,
    defaultLayer: 'mobilier',
    icon: 'shower',
    description: 'Receveur extra-plat avec paroi verre et caniveau',
    renderType: 'shower',
  },
  {
    id: 'block-double-vanity',
    name: 'Meuble Double Vasque',
    category: 'sanitaire',
    widthMm: 1400,
    heightMm: 550,
    defaultLayer: 'mobilier',
    icon: 'wash',
    description: 'Plan vasque céramique 2 robinetteries mitigeurs',
    renderType: 'sink',
  },
  {
    id: 'block-toilet-wallhung',
    name: 'WC Suspendu avec Bâti-Support',
    category: 'sanitaire',
    widthMm: 560,
    heightMm: 700,
    defaultLayer: 'mobilier',
    icon: 'wc',
    description: 'Cuvette sans bride avec coffrage technique',
    renderType: 'wc',
  },

  // MENUISERIES & OUVERTURES
  {
    id: 'block-door-interior-83',
    name: 'Porte Battante 830mm',
    category: 'menuiserie',
    widthMm: 830,
    heightMm: 830,
    defaultLayer: 'ouvertures',
    icon: 'meeting_room',
    description: 'Bloc-porte intérieur avec sens d\'ouverture à 90°',
    renderType: 'door',
  },
  {
    id: 'block-door-double-140',
    name: 'Double Porte Battante 1400mm',
    category: 'menuiserie',
    widthMm: 1400,
    heightMm: 700,
    defaultLayer: 'ouvertures',
    icon: 'door_sliding',
    description: 'Porte à deux vantaux égaux avec débattement double',
    renderType: 'door',
  },
  {
    id: 'block-sliding-bay-240',
    name: 'Baie Vitrée Coulissante 2.40m',
    category: 'menuiserie',
    widthMm: 2400,
    heightMm: 200,
    defaultLayer: 'ouvertures',
    icon: 'window',
    description: 'Baie alu 2 vantaux 2 rails rupture pont thermique',
    renderType: 'window',
  },

  // EXTÉRIEUR & TERRASSE
  {
    id: 'block-terrace-table',
    name: 'Table Extérieure & Fauteuils',
    category: 'exterieur',
    widthMm: 2000,
    heightMm: 1000,
    defaultLayer: 'mobilier',
    icon: 'deck',
    description: 'Mobilier de jardin teck et aluminium',
    renderType: 'table',
  },
  {
    id: 'block-sunbed',
    name: 'Bain de Soleil / Transat',
    category: 'exterieur',
    widthMm: 1950,
    heightMm: 650,
    defaultLayer: 'mobilier',
    icon: 'chair',
    description: 'Transat inclinable avec matelas étanche',
    renderType: 'generic',
  },
];
