import { MaterialDefinition } from '../types.ts';

export const ARCHITECTURAL_MATERIALS: MaterialDefinition[] = [
  {
    index: 'MAT-01',
    name: 'Béton Armé Banché C25/30',
    category: 'structure',
    density: '2 400 kg/m³',
    lambda: '1.75 W/m.K',
    acoustic: 'Rw = 58 dB',
    carbonIndex: 'B',
    color: '#4cd7f6',
    description: 'Voile porteur coulé en place pour façades et refends structurels',
  },
  {
    index: 'MAT-02',
    name: 'Placostil 72/48 Standard (BA13)',
    category: 'cloisons',
    density: '22 kg/m²',
    lambda: '0.25 W/m.K',
    acoustic: 'Rw = 42 dB',
    carbonIndex: 'A+',
    color: '#4edea3',
    description: 'Cloison sèche de distribution intérieure avec laine minérale 45mm',
  },
  {
    index: 'MAT-03',
    name: 'Placostil 98/48 Acoustique (Double BA13)',
    category: 'cloisons',
    density: '38 kg/m²',
    lambda: '0.22 W/m.K',
    acoustic: 'Rw = 53 dB',
    carbonIndex: 'A',
    color: '#34d399',
    description: 'Cloison séparative phonique renforcée pour suites et pièces d\'eau',
  },
  {
    index: 'MAT-04',
    name: 'Brique Monomur Terre Cuite 200mm',
    category: 'structure',
    density: '780 kg/m³',
    lambda: '0.12 W/m.K',
    acoustic: 'Rw = 51 dB',
    carbonIndex: 'A',
    color: '#ffb95f',
    description: 'Maçonnerie isolante respirante à rupture de pont thermique',
  },
  {
    index: 'MAT-05',
    name: 'Ossature Bois Épicéa C24 Massif',
    category: 'structure',
    density: '450 kg/m³',
    lambda: '0.13 W/m.K',
    acoustic: 'Rw = 46 dB',
    carbonIndex: 'A+',
    color: '#d97706',
    description: 'Montants et lisses certifiés PEFC bas carbone RE2020',
  },
  {
    index: 'MAT-06',
    name: 'Double Vitrage 4/16/4 Argon ITR',
    category: 'menuiserie',
    density: '20 kg/m²',
    lambda: '1.10 W/m².K (Ug)',
    acoustic: 'Rw = 34 dB',
    carbonIndex: 'A',
    color: '#38bdf8',
    description: 'Menuiserie aluminium thermolaqué à rupture de pont thermique',
  },
  {
    index: 'MAT-07',
    name: 'Chêne Massif Huilé Naturel',
    category: 'finition',
    density: '720 kg/m³',
    lambda: '0.18 W/m.K',
    acoustic: 'Rw = 38 dB',
    carbonIndex: 'A+',
    color: '#b45309',
    description: 'Menuiserie d\'agencement sur mesure et parquet d\'ébénisterie',
  },
  {
    index: 'MAT-08',
    name: 'Acier Thermolaqué Noir RAL 9005',
    category: 'menuiserie',
    density: '7 850 kg/m³',
    lambda: '50.0 W/m.K',
    acoustic: 'Rw = 44 dB',
    carbonIndex: 'B',
    color: '#94a3b8',
    description: 'Profilés fins pour verrière atelier type loft et séparations vitrées',
  },
  {
    index: 'MAT-09',
    name: 'Carrelage Grès Cérame 60x60 Grand Passage',
    category: 'finition',
    density: '2 300 kg/m³',
    lambda: '1.30 W/m.K',
    acoustic: 'Rw = 28 dB',
    carbonIndex: 'B',
    color: '#64748b',
    description: 'Revêtement de sol résistant aux pièces humides et zones techniques',
  },
  {
    index: 'MAT-10',
    name: 'Isolation Biosourcée Laine de Bois 140mm',
    category: 'isolation',
    density: '55 kg/m³',
    lambda: '0.036 W/m.K',
    acoustic: 'Rw = 48 dB',
    carbonIndex: 'A+',
    color: '#10b981',
    description: 'ITE écologique haute performance pour déphasage thermique estival',
  },
];
