import { CadEntity, CadLayer } from '../types.ts';

/** Calques normalisés d'un nouveau projet (structures, cloisons, ouvertures, mobilier, cotations). */
export const DEFAULT_LAYERS: CadLayer[] = [
  {
    id: 'structures',
    name: 'Structures porteuses (A-MUR-EXT)',
    category: 'structures',
    color: '#4cd7f6',
    visible: true,
    locked: false,
    opacity: 1,
    entityCount: 4,
    lineweight: '0.50mm',
    description: 'Murs extérieurs béton banché et chaînage',
  },
  {
    id: 'cloisons',
    name: 'Cloisons légères (A-MUR-INT)',
    category: 'cloisons',
    color: '#869397',
    visible: true,
    locked: false,
    opacity: 1,
    entityCount: 3,
    lineweight: '0.25mm',
    description: 'Cloisons Placostil 72mm et séparations intérieures',
  },
  {
    id: 'mobilier',
    name: 'Mobilier & Agencement (A-MOB-AGENC)',
    category: 'mobilier',
    color: '#4edea3',
    visible: true,
    locked: false,
    opacity: 1,
    entityCount: 5,
    lineweight: '0.15mm',
    description: 'Îlot cuisine, lit king size, meuble vasque, canapé',
  },
  {
    id: 'ouvertures',
    name: 'Menuiseries & Baies (A-PORTE-FEN)',
    category: 'ouvertures',
    color: '#ffb95f',
    visible: true,
    locked: false,
    opacity: 1,
    entityCount: 3,
    lineweight: '0.20mm',
    description: 'Portes battantes et baie coulissante 2800x2150',
  },
  {
    id: 'cotations',
    name: 'Cotations & Surfaces (A-COTE-TEXT)',
    category: 'cotations',
    color: '#acedff',
    visible: true,
    locked: false,
    opacity: 1,
    entityCount: 6,
    lineweight: '0.18mm',
    description: 'Lignes de cotes associatives et étiquettes m²',
  },
];

/** Projet d'exemple « Villa Horizon » (niveau RDC). */
export const SAMPLE_ENTITIES: CadEntity[] = [
  // STRUCTURES (Murs Porteurs Extérieurs)
  {
    id: 'wall-north',
    name: 'Mur Porteur Nord',
    type: 'wall',
    layerId: 'structures',
    x1: 140,
    y1: 160,
    x2: 740,
    y2: 160,
    thickness: 200,
    height: 2800,
    material: 'Béton banché + ITE 140mm',
    materialIndex: 'MAT-01',
  },
  {
    id: 'wall-west',
    name: 'Mur Porteur Ouest',
    type: 'wall',
    layerId: 'structures',
    x1: 140,
    y1: 690,
    x2: 140,
    y2: 160,
    thickness: 200,
    height: 2800,
    material: 'Béton banché + ITE 140mm',
    materialIndex: 'MAT-01',
  },
  {
    id: 'wall-south',
    name: 'Mur Porteur Sud',
    type: 'wall',
    layerId: 'structures',
    x1: 740,
    y1: 690,
    x2: 140,
    y2: 690,
    thickness: 200,
    height: 2800,
    material: 'Béton banché + ITE 140mm',
    materialIndex: 'MAT-01',
  },
  {
    id: 'wall-east',
    name: 'Mur Porteur Est',
    type: 'wall',
    layerId: 'structures',
    x1: 740,
    y1: 160,
    x2: 740,
    y2: 690,
    thickness: 200,
    height: 2800,
    material: 'Béton banché + ITE 140mm',
    materialIndex: 'MAT-01',
  },

  // CLOISONS
  {
    id: 'partition-salon-suite',
    name: 'Cloison Séparation Salon / Suite',
    type: 'partition',
    layerId: 'cloisons',
    x1: 140,
    y1: 460,
    x2: 420,
    y2: 460,
    thickness: 72,
    height: 2800,
    material: 'Placostil 72mm',
    materialIndex: 'MAT-02',
  },
  {
    id: 'partition-suite-sde',
    name: 'Cloison Suite / SDE',
    type: 'partition',
    layerId: 'cloisons',
    x1: 420,
    y1: 460,
    x2: 420,
    y2: 690,
    thickness: 72,
    height: 2800,
    material: 'Placostil 72mm',
    materialIndex: 'MAT-02',
  },
  {
    id: 'partition-cuisine-hall',
    name: 'Cloison Cuisine / Couloir',
    type: 'partition',
    layerId: 'cloisons',
    x1: 500,
    y1: 160,
    x2: 500,
    y2: 340,
    thickness: 72,
    height: 2800,
    material: 'Placostil 72mm',
    materialIndex: 'MAT-02',
  },

  // OUVERTURES (Encastrées directement dans les murs et cloisons)
  {
    id: 'door-suite',
    name: 'Porte Suite Parentale (830mm)',
    type: 'door',
    layerId: 'ouvertures',
    x1: 200,
    y1: 460,
    x2: 283,
    y2: 460,
    angle: 0,
    thickness: 72,
    hostWallId: 'partition-salon-suite',
    openingWidth: 830,
    doorSwing: 'right',
    doorAngle: 90,
    flipSwing: false,
    label: 'PORTE 830mm',
    materialIndex: 'MAT-07',
  },
  {
    id: 'door-sde',
    name: 'Porte Salle d\'eau (730mm)',
    type: 'door',
    layerId: 'ouvertures',
    x1: 420,
    y1: 500,
    x2: 420,
    y2: 573,
    angle: 90,
    thickness: 72,
    hostWallId: 'partition-suite-sde',
    openingWidth: 730,
    doorSwing: 'left',
    doorAngle: 90,
    flipSwing: false,
    label: 'PORTE 730mm',
    materialIndex: 'MAT-07',
  },
  {
    id: 'window-bay-salon',
    name: 'Baie Coulissante 1800x2150',
    type: 'window',
    layerId: 'ouvertures',
    x1: 140,
    y1: 220,
    x2: 140,
    y2: 400,
    angle: 90,
    thickness: 200,
    hostWallId: 'wall-west',
    openingWidth: 1800,
    label: 'BAIE COULISSANTE 1800x2150',
    materialIndex: 'MAT-06',
  },
  {
    id: 'window-cuisine',
    name: 'Fenêtre Cuisine 1200x1250',
    type: 'window',
    layerId: 'ouvertures',
    x1: 550,
    y1: 160,
    x2: 670,
    y2: 160,
    angle: 0,
    thickness: 200,
    hostWallId: 'wall-north',
    openingWidth: 1200,
    label: 'FENÊTRE 1200x1250',
    materialIndex: 'MAT-06',
  },

  // MOBILIER
  {
    id: 'furniture-kitchen-island',
    name: 'Îlot Central Cuisine',
    type: 'furniture',
    layerId: 'mobilier',
    x1: 545,
    y1: 265,
    x2: 675,
    y2: 320,
    label: 'ÎLOT CENTRAL',
    materialIndex: 'MAT-07',
  },
  {
    id: 'furniture-sofa',
    name: 'Canapé d\'angle Salon',
    type: 'furniture',
    layerId: 'mobilier',
    x1: 170,
    y1: 190,
    x2: 280,
    y2: 290,
    label: 'CANAPÉ SALON',
  },
  {
    id: 'furniture-bed',
    name: 'Lit King Size 160x200',
    type: 'furniture',
    layerId: 'mobilier',
    x1: 180,
    y1: 520,
    x2: 280,
    y2: 640,
    label: 'LIT 160x200',
  },
  {
    id: 'furniture-vanity',
    name: 'Meuble Double Vasque',
    type: 'furniture',
    layerId: 'mobilier',
    x1: 430,
    y1: 470,
    x2: 530,
    y2: 500,
    label: 'DOUBLE VASQUE',
  },

  // COTATIONS & SURFACES
  {
    id: 'dim-north',
    name: 'Cote Totale Façade Nord',
    type: 'dim',
    layerId: 'cotations',
    x1: 120,
    y1: 102,
    x2: 740,
    y2: 102,
    label: '7 200',
  },
  {
    id: 'dim-salon',
    name: 'Cote Largeur Salon',
    type: 'dim',
    layerId: 'cotations',
    x1: 140,
    y1: 124,
    x2: 500,
    y2: 124,
    label: '4 800',
  },
  {
    id: 'room-salon',
    name: 'Zone Salon de Réception',
    type: 'room',
    layerId: 'cotations',
    x1: 140,
    y1: 160,
    x2: 500,
    y2: 460,
    label: 'SALON DE RÉCEPTION',
    subText: 'PARQUET CHÊNE MASSIF',
    area: 32.40,
    height: 2.80,
    hatchPattern: 'bois',
  },
  {
    id: 'room-cuisine',
    name: 'Zone Cuisine Ouverte',
    type: 'room',
    layerId: 'cotations',
    x1: 500,
    y1: 160,
    x2: 720,
    y2: 340,
    label: 'CUISINE OUVERTE',
    area: 14.20,
    height: 2.80,
    hatchPattern: 'carrelage',
  },
  {
    id: 'room-suite',
    name: 'Zone Suite Parentale',
    type: 'room',
    layerId: 'cotations',
    x1: 140,
    y1: 460,
    x2: 420,
    y2: 680,
    label: 'SUITE PARENTALE',
    area: 18.50,
    height: 2.80,
    hatchPattern: 'bois',
  },
  {
    id: 'room-sde',
    name: 'Zone Salle d\'eau',
    type: 'room',
    layerId: 'cotations',
    x1: 420,
    y1: 460,
    x2: 560,
    y2: 680,
    label: 'SDE',
    area: 6.20,
    height: 2.80,
    hatchPattern: 'carrelage',
  },
];
